[remote.github]
owner = "alexander-bruun"
repo = "orb"

[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
{% endfor %}
{% endfor %}
{% if contributors is defined and contributors | length > 0 %}
### Contributors
{% for contributor in contributors | unique(attribute="username") %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
{% if previous.version %}
**Full Changelog**: https://github.com/alexander-bruun/orb/compare/{{ previous.version }}...{{ version }}
{% endif %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^feat\\(ui\\)", group = "UI" },
  { message = "^feat\\(api\\)", group = "API" },
  { message = "^feat\\(auth\\)", group = "Auth" },
  { message = "^feat\\(ingest\\)", group = "Ingest" },
  { message = "^feat\\(db\\)", group = "Database" },
  { message = "^feat\\(desktop\\)", group = "Desktop" },
  { message = "^feat\\(ci\\)", group = "CI" },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^chore", group = "Chores" },
  { message = "^build\\(deps\\)", skip = true },
  { message = ".*", group = "Other" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
